# Generated by Django 3.2.9 on 2021-11-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.AddField(
            model_name='address',
            name='mpesa_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='mpesa_phone_number',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
